@MusicBoxServer_HostAddress = http://localhost:5101  GET {{MusicBoxServer_HostAddress}}/weatherforecast/ Accept: application/json  ###  GET {{MusicBoxServer_HostAddress}}/weatherforecast  ###  POST {{MusicBoxServer_HostAddress}}/user/register Content-Type: application/json  {   "Username": "newuser",   "Password": "password123",   "Email": "newuser@example.com",   "Area": "TestArea" }  ### POST {{MusicBoxServer_HostAddress}}/user/login Content-Type: application/json  {   "Username": "newuser",   "Password": "password123" } ###  GET {{MusicBoxServer_HostAddress}}/user/userinfo?userID=1 Accept: application/json  ###